sudo: required 
language: generic

services: 
  - docker 

before_install: 
  - docker build -t p20min/react-test -f ./client/Dockerfile.dev ./client
  
scripts: 
  - docker run -e CI=true p20min/react-test npm test

after_success: 
  - docker build -t p20min/multi-client ./client
  - docker build -t p20min/multi-nginx ./nginx
  - docker build -t p20min/multi-server ./server
  - docker build -t p20min/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push p20min/multi-client
  - docker push p20min/multi-nginx 
  - docker push p20min/multi-server
  - docker push p20min/multi-worker


deploy: 


deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-496870371832
  bucket_path: docker-multi
  on: 
    branch: master 
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_ACCESS_KEY
